name: Android Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 55
    strategy:
      matrix:
        directory: [apps/paper] # , apps/fabric
    concurrency:
      group: android-ubuntu-${{ matrix.directory }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23

      - name: Set ANDROID_NDK
        run: echo "ANDROID_NDK=$ANDROID_HOME/ndk-bundle" >> $GITHUB_ENV

      - name: SDKs - accept licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      # Cache hermes build for both directories
      - name: Cache hermes build
        uses: actions/cache@v3
        env:
          cache-name: cache-rn-hermes-engine
        with:
          path: node_modules/react-native
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.directory }}-${{ hashFiles('**/react-native/package.json') }}

      # Cache android libraries for both directories
      - name: Cache android libraries
        uses: actions/cache@v3
        env:
          cache-name: cache-rn
        with:
          path: ${{ matrix.directory }}/android/app/build
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.directory }}-${{ hashFiles('**/react-native/package.json') }}

      # Build Android app in specified directories using matrix
      - name: Build Android app
        working-directory: ${{ matrix.directory }}/android
        run: ./gradlew assembleDebug

      # Cache apk for both directories
      - name: Cache apk
        uses: actions/cache/save@v3
        env:
          cache-name: cache-apk
        with:
          path: ${{ matrix.directory }}/android/app/build/outputs/apk/debug/app-debug.apk
          key: apk-${{ github.sha }}
