name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: tests-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      # - name: Run clang-format-ios
      #   working-directory: packages/skia
      #   run: yarn clang-format-ios --dry-run --Werror

      # - name: Run clang-format-android
      #   working-directory: packages/skia
      #   run: yarn clang-format-android --dry-run --Werror

      # - name: Run clang-format-common
      #   working-directory: packages/skia
      #   run: yarn clang-format-common --dry-run --Werror
  
      - name: Lint Example/Fabric Example
        run: yarn lint

      - name: TypeScript Example/Fabric Example
        run: yarn tsc

      - name: Run Example/Fabric Example Unit tests
        run: yarn test

      - name: TypeScript Example Docs
        run: cd apps/docs; yarn build;
